# Gunakan image Node.js LTS resmi
FROM node:18-alpine

# Setel direktori kerja di dalam kontainer
WORKDIR /app/backend

# Salin package.json dan package-lock.json untuk menginstal dependensi
COPY backend/package*.json ./

# Instal dependensi
RUN npm install

# Salin sisa kode aplikasi backend
COPY backend/ .

# Ekspos port yang didengarkan oleh aplikasi Express
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["npm", "start"]